### ISSUE TITLE
Calling `BLAKE3.hash` seems to freeze the whole thread.

### ISSUE THREAD

**Issue by JoshBashed** [nixberg/blake3-swift#6]
Hi, I'm developing a software that uses BLAKE3. I figured out that when I call hash, it runs forever. Here is a code snippet.
```swift
let dataBytes = [UInt8](data)
let hash = BLAKE3.hash(contentsOf: dataBytes)
return Data(hash) == Data(base64Encoded: artifact.hash.value
```
I don't really know why I am encountering this behavior.

**Comment by nixberg** [comment]
Could you share `dataBytes.count`? Are you running it in debug or release mode?

**Comment by JoshBashed** [comment]
Sure!
It's running in `debug` mode and the byte count is `169537860` (169 MB).

For now, I just am using bindings to the c library: https://github.com/JoshuaBrest/blake3-swift

**Comment by nixberg** [comment]
Yeah, sorry, it's just very slow in debug mode (and still slow in release).

I have something faster downstream  and upcoming Swift features like `Vector` and `RawSpan` are going to help with that but no promises when that will be released.

A wrapper for the official BLAKE3 library is a good thing that should exist anyway and is probably your best option right now, if you're dealing with non-trivial amounts of data.
